import { proto, WASocket, WAMessage } from '@whiskeysockets/baileys';
import { config } from '../config/index.js';
import { botSettings, MemberAccessMode } from '../config/settings.js';
import { aiService } from '../services/ai.js';
import { transcriberService } from '../services/transcriber.js';
import { imageService } from '../services/imageService.js';
import { memoryService } from '../services/memoryService.js';
import { reminderService } from '../services/reminderService.js';
import { searchService } from '../services/searchService.js';
import { documentService } from '../services/documentService.js';
import { expenseService } from '../services/expenseService.js';
import { ttsService } from '../services/ttsService.js';
import { imageGenService } from '../services/imageGenService.js';
import { logger } from '../utils/logger.js';

// Message buffer per chat for summarization and context
const recentGroupMessages = new Map<string, Array<{ sender: string; text: string; time: string }>>();

export class MessageHandler {
  /**
   * Main entry point for incoming messages
   */
  public async handleMessage(sock: WASocket, msg: WAMessage): Promise<void> {
    try {
      if (!msg.message || msg.key.remoteJid === 'status@broadcast') {
        return;
      }

      const chatId = msg.key.remoteJid;
      if (!chatId) return;

      const isGroup = chatId.endsWith('@g.us');
      const isFromMe = !!msg.key.fromMe;
      const senderJid = msg.key.participant || msg.key.remoteJid || '';
      const senderName = msg.pushName || 'User';
      const textContent = this.extractTextContent(msg.message);
      const isAudio = !!transcriberService.extractAudioMessage(msg.message);
      const myPhoneNumber = sock.user?.id ? sock.user.id.split(':')[0].replace(/[^0-9]/g, '') : '';
      const myLidNumber = sock.user?.lid ? sock.user.lid.split(':')[0].replace(/[^0-9]/g, '') : '';
      const pairingNumber = config.pairingPhoneNumber ? config.pairingPhoneNumber.replace(/[^0-9]/g, '') : '';
      const cleanSender = senderJid.replace(/[^0-9]/g, '');
      const isSelfChat = !isGroup && (cleanSender === myPhoneNumber || cleanSender === pairingNumber);
      const isOwner =
        isFromMe ||
        (!!myPhoneNumber && cleanSender.startsWith(myPhoneNumber)) ||
        (!!myLidNumber && cleanSender.startsWith(myLidNumber)) ||
        (!!pairingNumber && cleanSender.startsWith(pairingNumber)) ||
        config.adminNumbers.some(adminNum => cleanSender.startsWith(adminNum));

      // Loop & Echo Prevention: Ignore messages generated by the bot or fromMe without an explicit '!' prefix
      if (isFromMe && !textContent.startsWith('!') && !textContent.startsWith(config.commandPrefix)) {
        return;
      }

      if (
        textContent.includes('[Assistant]') ||
        textContent.startsWith('🤖') ||
        textContent.startsWith('⏳') ||
        textContent.startsWith('🔍') ||
        textContent.startsWith('⏰') ||
        textContent.startsWith('💰') ||
        textContent.startsWith('🧾')
      ) {
        return;
      }

      if (textContent || isAudio) {
        logger.info({ chatId, text: textContent?.slice(0, 60), isFromMe, isOwner, senderName }, '📨 Incoming message');
      }

      // Cache message for group summarization
      if (isGroup && textContent) {
        this.cacheGroupMessage(chatId, senderName, textContent);
      }

      const trimmedText = textContent.trim();
      const lowerText = trimmedText.toLowerCase();

      // Check if sender is a group admin
      const isGroupAdmin = isGroup ? await this.checkIsGroupAdmin(sock, chatId, senderJid, isFromMe) : isOwner;

      // -------------------------------------------------------------
      // 1. MASTER KILL SWITCH COMMANDS (Owner Only)
      // -------------------------------------------------------------
      if (
        lowerText === '!kill' ||
        lowerText === '!stop' ||
        lowerText === '!pause' ||
        lowerText === '!ai off' ||
        lowerText === '!bot off' ||
        lowerText === `${config.commandPrefix} kill` ||
        lowerText === `${config.commandPrefix} stop` ||
        lowerText === `${config.commandPrefix} pause` ||
        lowerText === `${config.commandPrefix} off`
      ) {
        if (!isOwner) {
          await sock.sendMessage(chatId, { text: '⛔ *Access Denied:* Only the bot owner (Tazim) can trigger the AI kill switch.' }, { quoted: msg });
          return;
        }
        botSettings.setAiKilled(true);
        await sock.sendMessage(
          chatId,
          {
            text: '🛑 *CARNIVORE AI KILLED / PAUSED*\n\nThe AI assistant has been completely stopped globally. It will not respond to any messages, mentions, wake words, voice notes, documents, or images in any chat.\n\n👉 *To resume AI:* Only Tazim (Owner) can send `!resume` or `!ai on` or `!start`.'
          },
          { quoted: msg }
        );
        return;
      }

      if (
        lowerText === '!resume' ||
        lowerText === '!start' ||
        lowerText === '!unpause' ||
        lowerText === '!ai on' ||
        lowerText === '!bot on' ||
        lowerText === `${config.commandPrefix} resume` ||
        lowerText === `${config.commandPrefix} start` ||
        lowerText === `${config.commandPrefix} on`
      ) {
        if (!isOwner) {
          await sock.sendMessage(chatId, { text: '⛔ *Access Denied:* Only the bot owner (Tazim) can resume Carnivore AI.' }, { quoted: msg });
          return;
        }
        botSettings.setAiKilled(false);
        await sock.sendMessage(
          chatId,
          {
            text: '✅ *CARNIVORE AI RESUMED / ONLINE*\n\nCarnivore is back online and actively listening for commands and messages!'
          },
          { quoted: msg }
        );
        return;
      }

      // -------------------------------------------------------------
      // 2. STATUS & PERMISSION OVERVIEW COMMANDS
      // -------------------------------------------------------------
      if (
        lowerText === '!status' ||
        lowerText === '!aistatus' ||
        lowerText === '!killswitch' ||
        lowerText === `${config.commandPrefix} status`
      ) {
        const isKilled = botSettings.isAiKilled;
        const mode = botSettings.memberAccessMode;
        const allowedCount = botSettings.allowedUsers.length;
        const blockedCount = botSettings.blockedUsers.length;
        const isCurrentChatDisabled = botSettings.isChatDisabled(chatId);

        const statusMsg =
          `🦁 *CARNIVORE AI ASSISTANT STATUS*\n` +
          `_Created & Developed by Tazim_\n\n` +
          `• *Kill Switch:* ${isKilled ? '🛑 *KILLED / PAUSED*' : '🟢 *ONLINE & ACTIVE*'}\n` +
          `• *Member Access Mode:* \`${mode.toUpperCase()}\`\n` +
          `• *This Chat AI Status:* ${isCurrentChatDisabled ? '🔴 Disabled' : '🟢 Enabled'}\n` +
          `• *Whitelisted Members:* ${allowedCount}\n` +
          `• *Blocked Members:* ${blockedCount}\n` +
          `• *DM Auto-Reply:* ${botSettings.autoReplyDms ? '🟢 Enabled' : '🔴 Disabled'}\n` +
          `• *AI Model:* \`${config.aiModel}\`\n\n` +
          `_Use \`!permissions\` to view detailed member access or \`!help\` for commands._`;

        await sock.sendMessage(chatId, { text: statusMsg }, { quoted: msg });
        return;
      }

      if (
        lowerText === '!permissions' ||
        lowerText === '!access' ||
        lowerText === '!users' ||
        lowerText === `${config.commandPrefix} permissions` ||
        lowerText === `${config.commandPrefix} access`
      ) {
        const mode = botSettings.memberAccessMode;
        const allowed = botSettings.allowedUsers;
        const blocked = botSettings.blockedUsers;
        const disabledChats = botSettings.disabledChats;

        let permMsg = `🛡️ *AI ACCESS CONTROL & PERMISSIONS*\n\n`;
        permMsg += `• *Current Access Mode:* \`${mode.toUpperCase()}\`\n`;
        permMsg += `  - \`all\`: All members can use AI\n`;
        permMsg += `  - \`whitelist\`: Only whitelisted members can use AI\n`;
        permMsg += `  - \`admin_only\`: Only group admins + owner can use AI\n`;
        permMsg += `  - \`disabled\`: Non-owner members cannot use AI\n\n`;

        permMsg += `👥 *Whitelisted / Allowed Users (${allowed.length}):*\n`;
        if (allowed.length === 0) {
          permMsg += `  _None (all members allowed unless blocked)_\n`;
        } else {
          permMsg += allowed.map(u => `  • \`${u}\``).join('\n') + '\n';
        }

        permMsg += `\n🚫 *Blocked Users (${blocked.length}):*\n`;
        if (blocked.length === 0) {
          permMsg += `  _None_\n`;
        } else {
          permMsg += blocked.map(u => `  • \`${u}\``).join('\n') + '\n';
        }

        permMsg += `\n🔇 *Disabled Chats (${disabledChats.length}):*\n`;
        if (disabledChats.length === 0) {
          permMsg += `  _None_\n`;
        } else {
          permMsg += disabledChats.map(c => `  • \`${c}\``).join('\n') + '\n';
        }

        permMsg += `\n💡 *Admin Commands:*
• \`!allow @user\` : Whitelist / unblock user
• \`!block @user\` / \`!deny @user\` : Block user
• \`!unblock @user\` : Unblock user
• \`!members <all|whitelist|admins|off>\` : Set mode
• \`!chat on / off\` : Toggle AI in this chat`;

        await sock.sendMessage(chatId, { text: permMsg }, { quoted: msg });
        return;
      }

      // -------------------------------------------------------------
      // 3. MEMBER ACCESS CONTROL MANAGEMENT (Owner or Admin)
      // -------------------------------------------------------------
      // Toggle Chat AI: !chat on / off or !group on / off
      if (
        lowerText === '!chat on' ||
        lowerText === '!chat off' ||
        lowerText === '!group on' ||
        lowerText === '!group off' ||
        lowerText.startsWith('!chat ') ||
        lowerText.startsWith('!group ')
      ) {
        if (!isOwner && !isGroupAdmin) {
          await sock.sendMessage(chatId, { text: '⛔ *Access Denied:* Only admins or bot owner can toggle chat AI.' }, { quoted: msg });
          return;
        }

        const action = lowerText.split(/\s+/)[1];
        if (action === 'on' || action === 'enable') {
          botSettings.enableChat(chatId);
          await sock.sendMessage(chatId, { text: '🟢 *AI Assistant is now ENABLED in this chat.*' }, { quoted: msg });
          return;
        } else if (action === 'off' || action === 'disable') {
          botSettings.disableChat(chatId);
          await sock.sendMessage(chatId, { text: '🔴 *AI Assistant is now DISABLED in this chat.* (Admins can type `!chat on` to re-enable)' }, { quoted: msg });
          return;
        } else {
          const isOff = botSettings.isChatDisabled(chatId);
          await sock.sendMessage(
            chatId,
            { text: `ℹ️ Chat AI status: ${isOff ? '🔴 Disabled' : '🟢 Enabled'}\n\n• Turn ON: \`!chat on\`\n• Turn OFF: \`!chat off\`` },
            { quoted: msg }
          );
          return;
        }
      }

      // Member Access Mode: !members <all|whitelist|admins|off>
      if (
        lowerText.startsWith('!members') ||
        lowerText.startsWith(`${config.commandPrefix} members`)
      ) {
        if (!isOwner && !isGroupAdmin) {
          await sock.sendMessage(chatId, { text: '⛔ *Access Denied:* Only admins or bot owner can change member permissions.' }, { quoted: msg });
          return;
        }

        const parts = lowerText.split(/\s+/);
        const modeInput = parts[1]?.toLowerCase();

        let newMode: MemberAccessMode | null = null;
        if (modeInput === 'all' || modeInput === 'on' || modeInput === 'everyone') newMode = 'all';
        else if (modeInput === 'whitelist' || modeInput === 'allowlist') newMode = 'whitelist';
        else if (modeInput === 'admins' || modeInput === 'admin' || modeInput === 'admin_only') newMode = 'admin_only';
        else if (modeInput === 'off' || modeInput === 'disabled' || modeInput === 'none') newMode = 'disabled';

        if (newMode) {
          botSettings.setMemberAccessMode(newMode);
          await sock.sendMessage(
            chatId,
            {
              text: `🛡️ *Member Access Mode Updated: \`${newMode.toUpperCase()}\`*\n\n` +
                (newMode === 'all' ? '✅ All members can freely interact with the AI (unless individually blocked).' :
                 newMode === 'whitelist' ? '📋 Only specifically whitelisted members (`!allow @user`) can use the AI.' :
                 newMode === 'admin_only' ? '👑 Only group admins and the bot owner can use the AI.' :
                 '🔒 All non-owner members are restricted from using the AI.')
            },
            { quoted: msg }
          );
          return;
        } else {
          await sock.sendMessage(
            chatId,
            {
              text: `🛡️ *Member Access Modes:*\n\n` +
                `• \`!members all\` : Allow all members to use AI\n` +
                `• \`!members whitelist\` : Restrict to whitelisted users\n` +
                `• \`!members admins\` : Restrict to group admins only\n` +
                `• \`!members off\` : Restrict all members\n\n` +
                `Current mode: \`${botSettings.memberAccessMode.toUpperCase()}\``
            },
            { quoted: msg }
          );
          return;
        }
      }

      // Allow / Whitelist User: !allow @user or !whitelist @user
      if (
        lowerText.startsWith('!allow') ||
        lowerText.startsWith('!whitelist') ||
        lowerText.startsWith(`${config.commandPrefix} allow`) ||
        lowerText.startsWith(`${config.commandPrefix} whitelist`)
      ) {
        if (!isOwner && !isGroupAdmin) {
          await sock.sendMessage(chatId, { text: '⛔ *Access Denied:* Only admins or bot owner can allow users.' }, { quoted: msg });
          return;
        }

        const target = this.extractTargetUser(msg, trimmedText);
        if (!target) {
          await sock.sendMessage(
            chatId,
            { text: '💡 Usage: `!allow @user` or `!allow +919876543210` (or reply to their message with `!allow`)' },
            { quoted: msg }
          );
          return;
        }

        const res = botSettings.allowUser(target);
        const display = target.includes('@') ? `@${target.split('@')[0].split(':')[0]}` : target;
        const unblockedText = res.wasBlocked ? ' (and removed from blocked list)' : '';

        await sock.sendMessage(
          chatId,
          {
            text: `✅ ${display} is now *ALLOWED / WHITELISTED* to use the AI assistant${unblockedText}.`,
            mentions: target.includes('@') ? [target] : undefined
          },
          { quoted: msg }
        );
        return;
      }

      // Block / Disallow User: !block @user, !disallow @user, !deny @user, !ban @user
      if (
        lowerText.startsWith('!block') ||
        lowerText.startsWith('!disallow') ||
        lowerText.startsWith('!deny') ||
        lowerText.startsWith('!ban') ||
        lowerText.startsWith(`${config.commandPrefix} block`) ||
        lowerText.startsWith(`${config.commandPrefix} disallow`)
      ) {
        if (!isOwner && !isGroupAdmin) {
          await sock.sendMessage(chatId, { text: '⛔ *Access Denied:* Only admins or bot owner can block users.' }, { quoted: msg });
          return;
        }

        const target = this.extractTargetUser(msg, trimmedText);
        if (!target) {
          await sock.sendMessage(
            chatId,
            { text: '💡 Usage: `!block @user` or `!disallow +919876543210` (or reply to their message with `!block`)' },
            { quoted: msg }
          );
          return;
        }

        const res = botSettings.blockUser(target);
        const display = target.includes('@') ? `@${target.split('@')[0].split(':')[0]}` : target;
        const removedText = res.wasAllowed ? ' (and removed from whitelist)' : '';

        await sock.sendMessage(
          chatId,
          {
            text: `🚫 ${display} is now *BLOCKED* from using the AI assistant${removedText}.`,
            mentions: target.includes('@') ? [target] : undefined
          },
          { quoted: msg }
        );
        return;
      }

      // Unblock User: !unblock @user
      if (
        lowerText.startsWith('!unblock') ||
        lowerText.startsWith(`${config.commandPrefix} unblock`)
      ) {
        if (!isOwner && !isGroupAdmin) {
          await sock.sendMessage(chatId, { text: '⛔ *Access Denied:* Only admins or bot owner can unblock users.' }, { quoted: msg });
          return;
        }

        const target = this.extractTargetUser(msg, trimmedText);
        if (!target) {
          await sock.sendMessage(
            chatId,
            { text: '💡 Usage: `!unblock @user` or `!unblock +919876543210`' },
            { quoted: msg }
          );
          return;
        }

        const success = botSettings.unblockUser(target);
        const display = target.includes('@') ? `@${target.split('@')[0].split(':')[0]}` : target;

        if (success) {
          await sock.sendMessage(
            chatId,
            {
              text: `✅ ${display} has been *UNBLOCKED*.`,
              mentions: target.includes('@') ? [target] : undefined
            },
            { quoted: msg }
          );
        } else {
          await sock.sendMessage(
            chatId,
            { text: `ℹ️ ${display} was not in the blocked list.` },
            { quoted: msg }
          );
        }
        return;
      }

      // -------------------------------------------------------------
      // 4. KILL SWITCH & ACCESS CONTROL ENFORCEMENT GATE
      // -------------------------------------------------------------
      // If AI is killed completely, silently ignore all messages from non-owners (zero credits, zero messages)
      if (botSettings.isAiKilled && !isOwner) {
        return;
      }

      // Evaluate permissions for the current user and chat
      const access = botSettings.canUserUseAi({
        senderJid,
        isFromMe: isOwner,
        isGroup,
        isGroupAdmin,
        chatId
      });

      // If user/chat is not allowed, silently drop message without sending anything (saves credits & avoids spam)
      if (!access.allowed) {
        return;
      }

      // -------------------------------------------------------------
      // 5. MEDIA INTELLIGENCE (Voice, Documents, Vision/Receipts)
      // -------------------------------------------------------------
      // Handle Voice Note / Audio Transcription (only if tagged, commanded, or self-chat)
      if (isAudio && config.autoTranscribeAudio) {
        const isCommandedOrTagged = this.isMentionedOrCommanded(msg, textContent, sock.user?.id);

        if (isCommandedOrTagged || (isSelfChat && !isFromMe)) {
          logger.info({ chatId, senderName }, 'Processing incoming voice note for transcription');
          const transcription = await transcriberService.handleAudioMessage(sock, msg);
          if (transcription) {
            await sock.sendMessage(chatId, { text: transcription }, { quoted: msg });
          }
          return;
        }
      }

      // Handle Document Analysis (PDF, CSV, TXT, Word)
      const docInfo = documentService.extractDocumentInfo(msg.message);
      if (docInfo) {
        const hasTrigger = this.isMentionedOrCommanded(msg, textContent, sock.user?.id);
        const lowerRaw = textContent.toLowerCase();
        const shouldProcessDoc =
          hasTrigger ||
          docInfo.isQuoted ||
          lowerRaw.includes('summarize') ||
          lowerRaw.includes('read') ||
          lowerRaw.includes('analyze') ||
          (!isGroup && botSettings.autoReplyDms) ||
          (isSelfChat && !isFromMe);

        if (shouldProcessDoc) {
          logger.info({ chatId, fileName: docInfo.fileName }, 'Processing document with AI');
          await sock.sendMessage(chatId, { text: `📄 *Reading & analyzing "${docInfo.fileName}" with AI...*` }, { quoted: msg });
          const reply = await documentService.handleDocumentAnalysis(msg, docInfo, textContent, senderName, chatId);
          await sock.sendMessage(chatId, { text: reply }, { quoted: msg });
          return;
        }
      }

      // Handle Image Analysis & Receipt Tracking (direct image or quoted image)
      const imageInfo = imageService.extractImageMessage(msg.message);
      if (imageInfo) {
        const hasTrigger = this.isMentionedOrCommanded(msg, textContent, sock.user?.id);
        const lowerRaw = textContent.toLowerCase();

        // Check if user is logging an expense from receipt
        if (lowerRaw.includes('expense') || lowerRaw.includes('receipt') || lowerRaw.includes('bill')) {
          await sock.sendMessage(chatId, { text: '🧾 *Scanning receipt with AI...*' }, { quoted: msg });
          const imgBuffer = await imageService.downloadImageBuffer(imageInfo.image);
          if (imgBuffer) {
            const reply = await expenseService.logExpenseFromReceipt(imgBuffer, imageInfo.image.mimetype || 'image/jpeg', chatId, senderName);
            await sock.sendMessage(chatId, { text: reply }, { quoted: msg });
          } else {
            await sock.sendMessage(chatId, { text: '⚠️ Could not download receipt image.' }, { quoted: msg });
          }
          return;
        }

        const shouldProcessImage =
          hasTrigger ||
          (imageInfo.isQuoted && (lowerRaw.startsWith(config.commandPrefix) || lowerRaw.includes('review') || lowerRaw.includes('describe') || lowerRaw.includes('what') || lowerRaw.includes('explain') || lowerRaw.includes('solve') || lowerRaw.includes('read') || lowerRaw.includes('summarize'))) ||
          (!isGroup && botSettings.autoReplyDms) ||
          (isSelfChat && !isFromMe);

        if (shouldProcessImage) {
          logger.info({ chatId, senderName, isQuoted: imageInfo.isQuoted }, 'Processing image for AI vision review & analysis');
          await sock.sendMessage(chatId, { text: '🔍 *Analyzing image with AI...*' }, { quoted: msg });

          let cleanPrompt = textContent
            .replace(new RegExp(`^${config.commandPrefix}\\s*`, 'i'), '')
            .trim();

          const reply = await imageService.handleImageAnalysis(
            imageInfo.image,
            cleanPrompt,
            senderName,
            chatId
          );
          await sock.sendMessage(chatId, { text: reply }, { quoted: msg });
          return;
        }
      }

      if (!textContent) return;

      // -------------------------------------------------------------
      // 6. STANDARD COMMANDS
      // -------------------------------------------------------------
      // Help command
      if (lowerText === '!help' || lowerText === `${config.commandPrefix} help`) {
        const helpMsg = this.getHelpMessage();
        await sock.sendMessage(chatId, { text: helpMsg }, { quoted: msg });
        return;
      }

      // Ping command
      if (lowerText === '!ping' || lowerText === `${config.commandPrefix} ping`) {
        const statusMsg = `🦁 *Carnivore AI Assistant is Active!*\n_Created by Tazim_\n\n• *Model:* \`${config.aiModel}\`\n• *Access Mode:* \`${botSettings.memberAccessMode.toUpperCase()}\`\n• *Memory:* Active\n• *Reminders:* Active\n• *Commands:* \`${config.commandPrefix}\`, \`!remember\`, \`!remind\`, \`!search\`, \`!expense\`, \`!imagine\`, \`!speak\`, \`!meet\`, \`!help\``;
        await sock.sendMessage(chatId, { text: statusMsg }, { quoted: msg });
        return;
      }

      // Memory Commands: !remember <fact>, !memories, !forget <id>
      if (lowerText.startsWith('!remember ') || lowerText.startsWith(`${config.commandPrefix} remember `)) {
        const fact = trimmedText.replace(/^!remember\s+/i, '').replace(new RegExp(`^${config.commandPrefix}\\s*remember\\s+`, 'i'), '').trim();
        if (!fact) {
          await sock.sendMessage(chatId, { text: '💡 Usage: `!remember <fact>` (e.g. `!remember my gym time is 7 AM`)' }, { quoted: msg });
          return;
        }
        const item = memoryService.storeMemory(chatId, fact);
        await sock.sendMessage(chatId, { text: `🧠 *Fact Remembered!*\n\n📌 "${item.fact}"\n🆔 \`#${item.id}\`\n\n_I will remember this across all our conversations._` }, { quoted: msg });
        return;
      }

      if (lowerText === '!memories' || lowerText === `${config.commandPrefix} memories`) {
        const memoryList = memoryService.listMemories(chatId);
        await sock.sendMessage(chatId, { text: memoryList }, { quoted: msg });
        return;
      }

      if (lowerText.startsWith('!forget ') || lowerText.startsWith(`${config.commandPrefix} forget `)) {
        const id = trimmedText.replace(/^!forget\s+/i, '').replace(new RegExp(`^${config.commandPrefix}\\s*forget\\s+`, 'i'), '').trim().replace(/^#/, '');
        const success = memoryService.forgetMemory(id);
        if (success) {
          await sock.sendMessage(chatId, { text: `🗑️ *Forgotten memory [#${id}] successfully.*` }, { quoted: msg });
        } else {
          await sock.sendMessage(chatId, { text: `⚠️ Memory with ID \`#${id}\` not found. Type \`!memories\` to see active IDs.` }, { quoted: msg });
        }
        return;
      }

      // Reminder Commands: !remind <time> to <task>, !reminders, !delreminder <id>
      if (lowerText.startsWith('!remind ') || lowerText.startsWith(`${config.commandPrefix} remind `)) {
        const prompt = trimmedText.replace(/^!remind\s+/i, '').replace(new RegExp(`^${config.commandPrefix}\\s*remind\\s+`, 'i'), '').trim();
        const res = reminderService.parseAndSchedule(chatId, senderName, prompt);
        await sock.sendMessage(chatId, { text: res.message }, { quoted: msg });
        return;
      }

      if (lowerText === '!reminders' || lowerText === `${config.commandPrefix} reminders`) {
        const remindersList = reminderService.listReminders(chatId);
        await sock.sendMessage(chatId, { text: remindersList }, { quoted: msg });
        return;
      }

      if (lowerText.startsWith('!delreminder ') || lowerText.startsWith(`${config.commandPrefix} delreminder `)) {
        const id = trimmedText.replace(/^!delreminder\s+/i, '').replace(new RegExp(`^${config.commandPrefix}\\s*delreminder\\s+`, 'i'), '').trim().replace(/^#/, '');
        const success = reminderService.deleteReminder(id);
        if (success) {
          await sock.sendMessage(chatId, { text: `🗑️ *Cancelled reminder [#${id}] successfully.*` }, { quoted: msg });
        } else {
          await sock.sendMessage(chatId, { text: `⚠️ Reminder with ID \`#${id}\` not found. Type \`!reminders\` to see active IDs.` }, { quoted: msg });
        }
        return;
      }

      // Live Web Search: !search <query> or !google <query> or !web <query>
      if (
        lowerText.startsWith('!search ') ||
        lowerText.startsWith('!google ') ||
        lowerText.startsWith('!web ') ||
        lowerText.startsWith(`${config.commandPrefix} search `)
      ) {
        const query = trimmedText
          .replace(/^!(search|google|web)\s+/i, '')
          .replace(new RegExp(`^${config.commandPrefix}\\s*search\\s+`, 'i'), '')
          .trim();

        if (!query) {
          await sock.sendMessage(chatId, { text: '💡 Usage: `!search <query>` (e.g. `!search latest AI news today`)' }, { quoted: msg });
          return;
        }

        await sock.sendMessage(chatId, { text: '🌐 *Searching the web in real-time...*' }, { quoted: msg });
        const searchReply = await searchService.searchAndSummarize(query, senderName);
        await sock.sendMessage(chatId, { text: searchReply }, { quoted: msg });
        return;
      }

      // Expense & Budget Commands: !expense <amount> <desc>, !expenses, !export expenses
      if (lowerText.startsWith('!expense ') || lowerText.startsWith(`${config.commandPrefix} expense `)) {
        const input = trimmedText.replace(/^!expense\s+/i, '').replace(new RegExp(`^${config.commandPrefix}\\s*expense\\s+`, 'i'), '').trim();
        const res = expenseService.logExpenseFromText(chatId, senderName, input);
        await sock.sendMessage(chatId, { text: res.message }, { quoted: msg });
        return;
      }

      if (lowerText === '!expenses' || lowerText === `${config.commandPrefix} expenses`) {
        const summary = expenseService.getExpenseSummary(chatId);
        await sock.sendMessage(chatId, { text: summary }, { quoted: msg });
        return;
      }

      if (lowerText === '!export expenses' || lowerText === '!export' || lowerText === `${config.commandPrefix} export expenses`) {
        const csv = expenseService.generateCSV(chatId);
        await sock.sendMessage(
          chatId,
          {
            document: csv.buffer,
            fileName: csv.filename,
            mimetype: 'text/csv',
            caption: '📊 *Here is your full expense ledger spreadsheet (.CSV)*'
          },
          { quoted: msg }
        );
        return;
      }

      // Voice Audio / TTS Command: !speak <text> or !tts <text>
      if (
        lowerText.startsWith('!speak ') ||
        lowerText.startsWith('!tts ') ||
        lowerText.startsWith(`${config.commandPrefix} speak `)
      ) {
        const speechText = trimmedText
          .replace(/^!(speak|tts)\s+/i, '')
          .replace(new RegExp(`^${config.commandPrefix}\\s*speak\\s+`, 'i'), '')
          .trim();

        if (!speechText) {
          await sock.sendMessage(chatId, { text: '💡 Usage: `!speak <text>` (e.g. `!speak Good morning! You have 3 meetings today`)' }, { quoted: msg });
          return;
        }

        await sock.sendMessage(chatId, { text: '🎙️ *Generating voice note...*' }, { quoted: msg });
        const audio = await ttsService.generateSpeechBuffer(speechText);
        if (audio) {
          await sock.sendMessage(chatId, { audio: audio.buffer, mimetype: audio.mimetype, ptt: true }, { quoted: msg });
        } else {
          await sock.sendMessage(chatId, { text: '⚠️ Failed to generate audio voice note.' }, { quoted: msg });
        }
        return;
      }

      // AI Image Generation: !imagine <prompt> or !draw <prompt>
      if (
        lowerText.startsWith('!imagine ') ||
        lowerText.startsWith('!draw ') ||
        lowerText.startsWith('!image ') ||
        lowerText.startsWith(`${config.commandPrefix} imagine `)
      ) {
        const imgPrompt = trimmedText
          .replace(/^!(imagine|draw|image)\s+/i, '')
          .replace(new RegExp(`^${config.commandPrefix}\\s*imagine\\s+`, 'i'), '')
          .trim();

        if (!imgPrompt) {
          await sock.sendMessage(chatId, { text: '💡 Usage: `!imagine <prompt>` (e.g. `!imagine cyberpunk sports car in rain 4k`' }, { quoted: msg });
          return;
        }

        await sock.sendMessage(chatId, { text: '🎨 *Generating AI image with Flux...*' }, { quoted: msg });
        const imgResult = await imageGenService.generateImage(imgPrompt);
        if (imgResult) {
          await sock.sendMessage(
            chatId,
            {
              image: imgResult.buffer,
              caption: `🎨 *AI Generated Image*\n📌 "${imgResult.prompt}"`
            },
            { quoted: msg }
          );
        } else {
          await sock.sendMessage(chatId, { text: '⚠️ Failed to generate image. Please try again.' }, { quoted: msg });
        }
        return;
      }

      // Explicit Meeting Command: !meet ... or !schedule ...
      if (
        lowerText.startsWith('!meet') ||
        lowerText.startsWith('!schedule') ||
        lowerText.startsWith(`${config.commandPrefix} meet`) ||
        lowerText.startsWith(`${config.commandPrefix} schedule`)
      ) {
        let schedulePrompt = trimmedText
          .replace(/^!meet\s*/i, '')
          .replace(/^!schedule\s*/i, '')
          .replace(new RegExp(`^${config.commandPrefix}\\s*(meet|schedule)\\s*`, 'i'), '')
          .trim();

        if (!schedulePrompt) {
          await sock.sendMessage(
            chatId,
            {
              text: `📅 *Meeting Scheduler Usage:*\n\nExample:\n• \`!meet Tomorrow at 3 PM with client@gmail.com for Project Discussion\`\n• \`!meet Next Monday 10:00 AM to 11:00 AM with team@gmail.com\`\n\nI will automatically create the Google Calendar event, generate a Google Meet link, and invite all email addresses!`
            },
            { quoted: msg }
          );
          return;
        }

        logger.info({ chatId, senderName, prompt: schedulePrompt }, 'Processing meeting schedule command');
        await sock.sendMessage(chatId, { text: '⏳ *Scheduling meeting and setting up Google Meet...*' }, { quoted: msg });
        const reply = await aiService.handleMeetingSchedule(schedulePrompt, senderName);
        await sock.sendMessage(chatId, { text: reply }, { quoted: msg });
        return;
      }

      // Group Admin Moderation Commands: !kick / !remove, !add, !promote, !demote, !invite, !link
      if (
        lowerText.startsWith('!kick') ||
        lowerText.startsWith('!remove') ||
        lowerText.startsWith('!add') ||
        lowerText.startsWith('!promote') ||
        lowerText.startsWith('!demote') ||
        lowerText.startsWith('!invite') ||
        lowerText.startsWith('!link') ||
        lowerText.startsWith(`${config.commandPrefix} kick`) ||
        lowerText.startsWith(`${config.commandPrefix} remove`) ||
        lowerText.startsWith(`${config.commandPrefix} add`) ||
        lowerText.startsWith(`${config.commandPrefix} promote`) ||
        lowerText.startsWith(`${config.commandPrefix} demote`) ||
        lowerText.startsWith(`${config.commandPrefix} invite`)
      ) {
        if (!isGroup) {
          await sock.sendMessage(chatId, { text: 'ℹ️ Group moderation commands only work in group chats.' }, { quoted: msg });
          return;
        }

        let action = '';
        if (lowerText.startsWith('!kick') || lowerText.startsWith('!remove') || lowerText.startsWith(`${config.commandPrefix} kick`) || lowerText.startsWith(`${config.commandPrefix} remove`)) action = 'remove';
        else if (lowerText.startsWith('!add') || lowerText.startsWith(`${config.commandPrefix} add`)) action = 'add';
        else if (lowerText.startsWith('!promote') || lowerText.startsWith(`${config.commandPrefix} promote`)) action = 'promote';
        else if (lowerText.startsWith('!demote') || lowerText.startsWith(`${config.commandPrefix} demote`)) action = 'demote';
        else if (lowerText.startsWith('!invite') || lowerText.startsWith('!link') || lowerText.startsWith(`${config.commandPrefix} invite`)) action = 'invite';

        await this.handleGroupModeration(sock, msg, chatId, action, trimmedText, isFromMe, senderJid);
        return;
      }

      // Summarize command in groups
      if (lowerText.startsWith('!summarize') || lowerText.startsWith(`${config.commandPrefix} summarize`)) {
        if (!isGroup) {
          await sock.sendMessage(chatId, { text: 'ℹ️ The `!summarize` command is meant for group chats to summarize recent discussions.' }, { quoted: msg });
          return;
        }

        const countMatch = trimmedText.match(/\d+/);
        const count = countMatch ? Math.min(parseInt(countMatch[0], 10), 50) : 25;

        const history = recentGroupMessages.get(chatId) || [];
        const messagesToSummarize = history.slice(-count).map(m => `[${m.time}] ${m.sender}: ${m.text}`);

        if (messagesToSummarize.length < 3) {
          await sock.sendMessage(chatId, { text: 'ℹ️ Not enough recent messages recorded yet to generate a summary. Keep chatting and try again!' }, { quoted: msg });
          return;
        }

        await sock.sendMessage(chatId, { text: '⏳ *Analyzing and summarizing recent group messages...*' }, { quoted: msg });
        const summary = await aiService.summarizeMessages(messagesToSummarize);
        await sock.sendMessage(chatId, { text: `📊 *Group Chat Summary (Last ${messagesToSummarize.length} messages):*\n\n${summary}` }, { quoted: msg });
        return;
      }

      // Persistent Auto-Reply Toggle Command: !autoreply on / off
      if (
        lowerText === '!autoreply' ||
        lowerText.startsWith('!autoreply ') ||
        lowerText === `${config.commandPrefix} autoreply` ||
        lowerText.startsWith(`${config.commandPrefix} autoreply `)
      ) {
        const parts = lowerText.split(/\s+/);
        const subcommand = parts[1]?.toLowerCase();

        if (subcommand === 'on' || subcommand === 'enable' || subcommand === 'true') {
          botSettings.setAutoReplyDms(true);
          await sock.sendMessage(
            chatId,
            { text: '🤖 *Auto-Reply Mode: ON*\n\nThe bot will now automatically respond to all incoming direct messages (DMs) without needing `@bot` or `!ai`.' },
            { quoted: msg }
          );
          return;
        } else if (subcommand === 'off' || subcommand === 'disable' || subcommand === 'false') {
          botSettings.setAutoReplyDms(false);
          await sock.sendMessage(
            chatId,
            { text: '🔇 *Auto-Reply Mode: OFF (Tag / Command Only)*\n\nThe bot will now only reply when explicitly tagged (@bot) or commanded with `!ai`.' },
            { quoted: msg }
          );
          return;
        } else {
          const status = botSettings.autoReplyDms ? '🟢 *ENABLED (Auto-answers DMs)*' : '🔴 *DISABLED (Only answers when tagged or commanded)*';
          await sock.sendMessage(
            chatId,
            {
              text: `⚙️ *Auto-Reply Setting:* ${status}\n\n• Turn ON: \`!autoreply on\`\n• Turn OFF: \`!autoreply off\``
            },
            { quoted: msg }
          );
          return;
        }
      }

      // Explicit AI Command: !ai <prompt>
      if (lowerText.startsWith(config.commandPrefix)) {
        const prompt = trimmedText.slice(config.commandPrefix.length).trim();
        if (!prompt) {
          await sock.sendMessage(chatId, { text: `👋 Hi ${senderName}! How can I help you? Ask me anything by typing \`${config.commandPrefix} <your question>\`.` }, { quoted: msg });
          return;
        }

        // Check if prompt is a group moderation request in natural language
        if (isGroup && this.isGroupModerationIntent(prompt)) {
          const modAction = this.extractModerationAction(prompt);
          if (modAction) {
            await this.handleGroupModeration(sock, msg, chatId, modAction, prompt, isFromMe, senderJid);
            return;
          }
        }

        // Check if prompt is a meeting scheduling request
        if (this.isMeetingIntent(prompt)) {
          logger.info({ chatId, senderName, prompt }, 'Detected meeting scheduling intent in AI prompt');
          await sock.sendMessage(chatId, { text: '⏳ *Scheduling meeting and setting up Google Meet...*' }, { quoted: msg });
          const reply = await aiService.handleMeetingSchedule(prompt, senderName);
          await sock.sendMessage(chatId, { text: reply }, { quoted: msg });
          return;
        }

        logger.info({ chatId, senderName, prompt }, 'Processing AI command');
        const reply = await aiService.generateReply(chatId, prompt, senderName, isGroup);
        await sock.sendMessage(chatId, { text: reply }, { quoted: msg });
        return;
      }

      // Tag / Mention / Wake Word Trigger (in groups or DMs)
      const myJid = sock.user?.id ? sock.user.id.split(':')[0] + '@s.whatsapp.net' : '';
      const myLid = sock.user?.lid ? sock.user.lid.split(':')[0] + '@lid' : '';
      const isTagged = config.respondOnTag && (this.isUserTagged(msg, myJid) || this.isUserTagged(msg, myLid));
      const hasWakeWord = config.wakeWords.some(w => {
        const regex = new RegExp(`(^|\\s|@)${w}\\b`, 'i');
        return regex.test(lowerText);
      });

      if (isTagged || hasWakeWord) {
        // Clean prompt from tags / wake words
        let cleanedPrompt = trimmedText;
        if (myJid) {
          const myNum = myJid.split('@')[0];
          cleanedPrompt = cleanedPrompt.replace(new RegExp(`@${myNum}`, 'gi'), '').trim();
        }
        if (myLid) {
          const myLidNum = myLid.split('@')[0];
          cleanedPrompt = cleanedPrompt.replace(new RegExp(`@${myLidNum}`, 'gi'), '').trim();
        }
        config.wakeWords.forEach(w => {
          cleanedPrompt = cleanedPrompt.replace(new RegExp(`^@?${w}[: ,]?`, 'gi'), '').trim();
        });

        if (!cleanedPrompt) {
          await sock.sendMessage(
            chatId,
            { text: `👋 Hi ${senderName}! I'm listening. Ask me anything or type \`${config.commandPrefix} <your question>\` or \`!help\`.` },
            { quoted: msg }
          );
          return;
        }

        if (isGroup && this.isGroupModerationIntent(cleanedPrompt)) {
          const modAction = this.extractModerationAction(cleanedPrompt);
          if (modAction) {
            await this.handleGroupModeration(sock, msg, chatId, modAction, cleanedPrompt, isFromMe, senderJid);
            return;
          }
        }

        if (this.isMeetingIntent(cleanedPrompt)) {
          logger.info({ chatId, senderName, prompt: cleanedPrompt }, 'Responding to tagged meeting schedule intent');
          await sock.sendMessage(chatId, { text: '⏳ *Scheduling meeting and setting up Google Meet...*' }, { quoted: msg });
          const reply = await aiService.handleMeetingSchedule(cleanedPrompt, senderName);
          await sock.sendMessage(chatId, { text: reply }, { quoted: msg });
          return;
        }

        logger.info({ chatId, senderName, prompt: cleanedPrompt }, 'Responding to tag / mention / wake word');
        const reply = await aiService.generateReply(chatId, cleanedPrompt, senderName, isGroup);
        await sock.sendMessage(chatId, { text: reply }, { quoted: msg });
        return;
      }

      // Safe Direct Message Auto-Reply (Only active if autoReplyDms is explicitly turned ON)
      if (!isGroup && botSettings.autoReplyDms && !isFromMe) {
        logger.info({ chatId, senderName }, 'Auto-replying to direct message (autoReplyDms is ON)');
        const reply = await aiService.generateReply(chatId, trimmedText, senderName, false);
        await sock.sendMessage(chatId, { text: reply }, { quoted: msg });
        return;
      }
    } catch (err: any) {
      logger.error({ err: err?.message || err }, 'Error handling message');
    }
  }

  /**
   * Checks whether sender is an admin in a group chat
   */
  private async checkIsGroupAdmin(sock: WASocket, chatId: string, senderJid: string, isFromMe: boolean): Promise<boolean> {
    if (isFromMe) return true;
    try {
      const groupMeta = await sock.groupMetadata(chatId);
      const cleanSender = senderJid.split('@')[0].split(':')[0];
      const participant = groupMeta.participants.find(p => p.id.split('@')[0].split(':')[0] === cleanSender);
      return participant?.admin === 'admin' || participant?.admin === 'superadmin';
    } catch {
      return false;
    }
  }

  /**
   * Helper to extract target user JID from message context, mentions, or phone number in text
   */
  private extractTargetUser(msg: WAMessage, text: string): string | null {
    const quotedParticipant =
      msg.message?.extendedTextMessage?.contextInfo?.participant ||
      msg.message?.ephemeralMessage?.message?.extendedTextMessage?.contextInfo?.participant;
    if (quotedParticipant) return quotedParticipant;

    const mentionedJid =
      msg.message?.extendedTextMessage?.contextInfo?.mentionedJid?.[0] ||
      msg.message?.ephemeralMessage?.message?.extendedTextMessage?.contextInfo?.mentionedJid?.[0];
    if (mentionedJid) return mentionedJid;

    const phoneMatch = text.match(/(?:\+?\d{1,3})?[-.\s]?\(?\d{3,4}\)?[-.\s]?\d{3,4}[-.\s]?\d{3,4}/);
    if (phoneMatch) {
      let cleaned = phoneMatch[0].replace(/[^0-9]/g, '');
      if (cleaned.length === 10) cleaned = '91' + cleaned;
      return `${cleaned}@s.whatsapp.net`;
    }

    return null;
  }

  /**
   * Handles group moderation actions
   */
  private async handleGroupModeration(
    sock: WASocket,
    msg: WAMessage,
    chatId: string,
    action: string,
    rawText: string,
    isSenderFromMe: boolean,
    senderJid: string
  ): Promise<void> {
    try {
      const groupMeta = await sock.groupMetadata(chatId);
      const myJid = sock.user?.id ? sock.user.id.split(':')[0] + '@s.whatsapp.net' : '';
      const myLid = sock.user?.lid ? sock.user.lid.split(':')[0] + '@lid' : '';

      const myParticipant = groupMeta.participants.find(p => p.id === myJid || (myLid && p.id === myLid));
      const isBotAdmin = myParticipant?.admin === 'admin' || myParticipant?.admin === 'superadmin';

      if (!isBotAdmin) {
        await sock.sendMessage(
          chatId,
          { text: '⚠️ *I need Admin permissions in this group* to add, remove, promote, or manage members.' },
          { quoted: msg }
        );
        return;
      }

      const senderParticipant = groupMeta.participants.find(p => p.id === senderJid);
      const isSenderAdmin = isSenderFromMe || senderParticipant?.admin === 'admin' || senderParticipant?.admin === 'superadmin';

      if (!isSenderAdmin && action !== 'invite') {
        await sock.sendMessage(
          chatId,
          { text: '⛔ *Only group admins can use moderation commands.*' },
          { quoted: msg }
        );
        return;
      }

      // Action: Get invite link
      if (action === 'invite') {
        const inviteCode = await sock.groupInviteCode(chatId);
        const inviteUrl = `https://chat.whatsapp.com/${inviteCode}`;
        await sock.sendMessage(
          chatId,
          { text: `🔗 *Group Invite Link:*\n${inviteUrl}\n\n_Share this link for people to join._` },
          { quoted: msg }
        );
        return;
      }

      const targetJid = this.extractTargetUser(msg, rawText);

      if (!targetJid) {
        await sock.sendMessage(
          chatId,
          {
            text: `⚠️ *Please mention, reply to, or provide the phone number of the target user.*\n\nExamples:\n• \`!${action} @user\`\n• Reply to their message with \`!${action}\`\n• \`!add +919876543210\``
          },
          { quoted: msg }
        );
        return;
      }

      const targetDisplay = `@${targetJid.split('@')[0]}`;

      if (action === 'remove') {
        await sock.groupParticipantsUpdate(chatId, [targetJid], 'remove');
        await sock.sendMessage(chatId, { text: `✅ 👢 Removed ${targetDisplay} from group.`, mentions: [targetJid] });
      } else if (action === 'add') {
        const addResponse = await sock.groupParticipantsUpdate(chatId, [targetJid], 'add');
        const status = addResponse?.[0]?.status;

        if (status === '403') {
          const inviteCode = await sock.groupInviteCode(chatId);
          await sock.sendMessage(
            chatId,
            {
              text: `⚠️ Could not add ${targetDisplay} directly (their privacy settings or Community settings require an invite).\n\n🔗 *Invite Link:* https://chat.whatsapp.com/${inviteCode}`,
              mentions: [targetJid]
            }
          );
        } else {
          await sock.sendMessage(chatId, { text: `✅ ➕ Added ${targetDisplay} to group.`, mentions: [targetJid] });
        }
      } else if (action === 'promote') {
        await sock.groupParticipantsUpdate(chatId, [targetJid], 'promote');
        await sock.sendMessage(chatId, { text: `✅ ⭐ Promoted ${targetDisplay} to group admin!`, mentions: [targetJid] });
      } else if (action === 'demote') {
        await sock.groupParticipantsUpdate(chatId, [targetJid], 'demote');
        await sock.sendMessage(chatId, { text: `✅ 🔻 Demoted ${targetDisplay} from admin.`, mentions: [targetJid] });
      }
    } catch (err: any) {
      logger.error({ err: err?.message || err }, 'Error executing group moderation action');
      await sock.sendMessage(chatId, { text: `⚠️ Failed to execute moderation action: ${err?.message || 'Permission denied or invalid user'}` }, { quoted: msg });
    }
  }

  private isGroupModerationIntent(text: string): boolean {
    const lower = text.toLowerCase();
    return (
      lower.includes('kick ') ||
      lower.includes('remove ') ||
      lower.includes('add ') ||
      lower.includes('promote ') ||
      lower.includes('demote ') ||
      lower.includes('invite link') ||
      lower.includes('group link')
    );
  }

  private extractModerationAction(text: string): string | null {
    const lower = text.toLowerCase();
    if (lower.includes('kick') || lower.includes('remove')) return 'remove';
    if (lower.includes('add')) return 'add';
    if (lower.includes('promote') || lower.includes('make admin')) return 'promote';
    if (lower.includes('demote') || lower.includes('remove admin')) return 'demote';
    if (lower.includes('invite') || lower.includes('link')) return 'invite';
    return null;
  }

  private extractTextContent(message?: proto.IMessage | null): string {
    if (!message) return '';
    return (
      message.conversation ||
      message.extendedTextMessage?.text ||
      message.imageMessage?.caption ||
      message.videoMessage?.caption ||
      message.documentMessage?.caption ||
      message.ephemeralMessage?.message?.conversation ||
      message.ephemeralMessage?.message?.extendedTextMessage?.text ||
      message.ephemeralMessage?.message?.imageMessage?.caption ||
      ''
    );
  }

  private isMentionedOrCommanded(msg: WAMessage, text: string, myJid?: string): boolean {
    const lower = text.toLowerCase();
    if (lower.startsWith(config.commandPrefix) || lower.startsWith('!')) return true;

    if (myJid) {
      const myPhoneNumber = myJid.split(':')[0];
      if (this.isUserTagged(msg, `${myPhoneNumber}@s.whatsapp.net`)) return true;
    }

    return config.wakeWords.some(w => {
      const regex = new RegExp(`(^|\\s|@)${w}\\b`, 'i');
      return regex.test(lower);
    });
  }

  private isUserTagged(msg: WAMessage, userJid: string): boolean {
    if (!userJid) return false;
    const mentionedJids =
      msg.message?.extendedTextMessage?.contextInfo?.mentionedJid ||
      msg.message?.ephemeralMessage?.message?.extendedTextMessage?.contextInfo?.mentionedJid ||
      [];
    return mentionedJids.includes(userJid);
  }

  private cacheGroupMessage(chatId: string, sender: string, text: string) {
    if (!recentGroupMessages.has(chatId)) {
      recentGroupMessages.set(chatId, []);
    }
    const history = recentGroupMessages.get(chatId)!;
    const time = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    history.push({ sender, text, time });
    if (history.length > 50) {
      history.shift();
    }
  }

  private isMeetingIntent(text: string): boolean {
    const lower = text.toLowerCase();
    const meetingKeywords = [
      'schedule a meet',
      'schedule a meeting',
      'schedule meet',
      'schedule meeting',
      'create a meet',
      'create a meeting',
      'set up a meet',
      'set up a meeting',
      'book a meet',
      'book a meeting',
      'google meet',
      'calendar invite',
      'add to calendar',
      'meeting on',
      'meet on',
      'meet at',
      'meeting at',
      'meeting tomorrow',
      'meet tomorrow'
    ];
    return meetingKeywords.some(kw => lower.includes(kw));
  }

  private getHelpMessage(): string {
    return `🦁 *CARNIVORE AI EXECUTIVE ASSISTANT - COMMANDS*
_Created & Developed by Tazim_

🛑 *Kill Switch & Master Control:*
• \`!kill\` / \`!pause\` / \`!ai off\` : Turn AI completely OFF
• \`!resume\` / \`!start\` / \`!ai on\` : Turn AI back ON
• \`!status\` : View AI & kill switch status

🛡️ *Member Permissions & Access Control:*
• \`!allow @user\` : Whitelist / allow a user
• \`!block @user\` / \`!deny @user\` : Disallow / block a user
• \`!unblock @user\` : Remove user from block list
• \`!members <all|whitelist|admins|off>\` : Set global member mode
• \`!chat on / off\` : Toggle AI in this specific chat
• \`!permissions\` : View allowed/blocked list & active mode

🧠 *Long-Term Memory & Knowledge:*
• \`!remember <fact>\` : Save fact (e.g. \`!remember my gym time is 7 AM\`)
• \`!memories\` : View all saved memories & preferences
• \`!forget <ID>\` : Delete a stored memory

⏰ *Proactive Scheduled Reminders:*
• \`!remind in 30 mins to <task>\` : Schedule a reminder
• \`!remind tomorrow at 9:00 AM to <task>\` : Schedule future reminder
• \`!reminders\` : List all active reminders
• \`!delreminder <ID>\` : Cancel a reminder

🌐 *Real-Time Web Search:*
• \`!search <query>\` : Search the web live (e.g. \`!search latest tech news\`)

💰 *Expense & Receipt Tracker:*
• \`!expense <amount> <desc>\` : Log expense (e.g. \`!expense 450 lunch\`)
• *Send photo of Receipt* : Automatically scans & logs items & amount
• \`!expenses\` : View spending budget breakdown
• \`!export expenses\` : Download complete .CSV spreadsheet

🎨 *AI Image Generation:*
• \`!imagine <prompt>\` : Generate high-res AI image (e.g. \`!imagine cyberpunk city\`)

🎙️ *Voice Notes & Text-to-Speech:*
• \`!speak <text>\` : Generate a voice note audio reply
• *Send Voice Note* : Automatically transcribes audio to text

📄 *Document & PDF Intelligence:*
• *Send PDF / CSV / Doc* : AI reads, summarizes, and answers questions

📅 *Google Meet & Calendar:*
• \`!meet <details>\` : Schedule event & generate Meet link

🛡️ *Group Administration:*
• \`!kick / !remove @user\` : Remove user
• \`!add <phone>\` : Add user
• \`!promote / !demote @user\` : Manage admin status
• \`!invite / !link\` : Group invite link
• \`!summarize [n]\` : Summarize last [n] messages

⚙️ *Settings:*
• \`!autoreply on / off\` : Toggle auto-answering DMs
• \`!ping\` : Bot connection & model status`;
  }
}

export const messageHandler = new MessageHandler();
