import { proto, WASocket, WAMessage } from '@whiskeysockets/baileys';
import { config } from '../config/index.js';
import { botSettings } from '../config/settings.js';
import { aiService } from '../services/ai.js';
import { transcriberService } from '../services/transcriber.js';
import { imageService } from '../services/imageService.js';
import { logger } from '../utils/logger.js';

// Message buffer per chat for summarization and context
const recentGroupMessages = new Map<string, Array<{ sender: string; text: string; time: string }>>();

export class MessageHandler {
  /**
   * Main entry point for incoming messages
   */
  public async handleMessage(sock: WASocket, msg: WAMessage): Promise<void> {
    try {
      if (!msg.message || msg.key.remoteJid === 'status@broadcast') {
        return;
      }

      const chatId = msg.key.remoteJid;
      if (!chatId) return;

      const isGroup = chatId.endsWith('@g.us');
      const isFromMe = !!msg.key.fromMe;
      const senderJid = msg.key.participant || msg.key.remoteJid || '';
      const senderName = msg.pushName || 'User';
      const textContent = this.extractTextContent(msg.message);
      const isAudio = !!transcriberService.extractAudioMessage(msg.message);
      const myPhoneNumber = sock.user?.id ? sock.user.id.split(':')[0] : '';
      const isSelfChat = !isGroup && chatId.split('@')[0] === myPhoneNumber;

      // Loop & Echo Prevention: Ignore messages generated by the bot or fromMe without an explicit '!' prefix
      if (isFromMe && !textContent.startsWith('!') && !textContent.startsWith(config.commandPrefix)) {
        return;
      }

      if (textContent.includes('[Assistant]') || textContent.startsWith('🤖') || textContent.startsWith('⏳') || textContent.startsWith('🔍')) {
        return;
      }

      if (textContent || isAudio) {
        logger.info({ chatId, text: textContent?.slice(0, 60), isFromMe, senderName }, '📨 Incoming message');
      }

      // Cache message for group summarization
      if (isGroup && textContent) {
        this.cacheGroupMessage(chatId, senderName, textContent);
      }

      // Handle Voice Note / Audio Transcription (only if tagged, commanded, or self-chat)
      if (isAudio && config.autoTranscribeAudio) {
        const isCommandedOrTagged = this.isMentionedOrCommanded(msg, textContent, sock.user?.id);

        if (isCommandedOrTagged || (isSelfChat && !isFromMe)) {
          logger.info({ chatId, senderName }, 'Processing incoming voice note for transcription');
          const transcription = await transcriberService.handleAudioMessage(sock, msg);
          if (transcription) {
            await sock.sendMessage(chatId, { text: transcription }, { quoted: msg });
          }
          return;
        }
      }

      // Handle Image Analysis (direct image or quoted image)
      const imageInfo = imageService.extractImageMessage(msg.message);
      if (imageInfo) {
        const hasTrigger = this.isMentionedOrCommanded(msg, textContent, sock.user?.id);
        const lowerRaw = textContent.toLowerCase();
        const shouldProcessImage =
          hasTrigger ||
          (imageInfo.isQuoted && (lowerRaw.startsWith(config.commandPrefix) || lowerRaw.includes('review') || lowerRaw.includes('describe') || lowerRaw.includes('what') || lowerRaw.includes('explain') || lowerRaw.includes('solve') || lowerRaw.includes('read') || lowerRaw.includes('summarize'))) ||
          (!isGroup && botSettings.autoReplyDms) ||
          (isSelfChat && !isFromMe);

        if (shouldProcessImage) {
          logger.info({ chatId, senderName, isQuoted: imageInfo.isQuoted }, 'Processing image for AI vision review & analysis');
          await sock.sendMessage(chatId, { text: '🔍 *Analyzing image with AI...*' }, { quoted: msg });

          let cleanPrompt = textContent
            .replace(new RegExp(`^${config.commandPrefix}\\s*`, 'i'), '')
            .trim();

          const reply = await imageService.handleImageAnalysis(
            imageInfo.image,
            cleanPrompt,
            senderName,
            chatId
          );
          await sock.sendMessage(chatId, { text: reply }, { quoted: msg });
          return;
        }
      }

      if (!textContent) return;

      const trimmedText = textContent.trim();
      const lowerText = trimmedText.toLowerCase();

      // Help command
      if (lowerText === '!help' || lowerText === `${config.commandPrefix} help`) {
        const helpMsg = this.getHelpMessage();
        await sock.sendMessage(chatId, { text: helpMsg }, { quoted: msg });
        return;
      }

      // Ping command
      if (lowerText === '!ping' || lowerText === `${config.commandPrefix} ping`) {
        const statusMsg = `🤖 *WhatsApp AI Assistant is Active!*\n\n• *Model:* \`${config.aiModel}\`\n• *Mode:* Tag/Command only (safe for all chats)\n• *Commands:* \`${config.commandPrefix}\`, \`!meet\`, \`!summarize\`, \`!ping\`, \`!help\``;
        await sock.sendMessage(chatId, { text: statusMsg }, { quoted: msg });
        return;
      }

      // Explicit Meeting Command: !meet ... or !schedule ...
      if (
        lowerText.startsWith('!meet') ||
        lowerText.startsWith('!schedule') ||
        lowerText.startsWith(`${config.commandPrefix} meet`) ||
        lowerText.startsWith(`${config.commandPrefix} schedule`)
      ) {
        let schedulePrompt = trimmedText
          .replace(/^!meet\s*/i, '')
          .replace(/^!schedule\s*/i, '')
          .replace(new RegExp(`^${config.commandPrefix}\\s*(meet|schedule)\\s*`, 'i'), '')
          .trim();

        if (!schedulePrompt) {
          await sock.sendMessage(
            chatId,
            {
              text: `📅 *Meeting Scheduler Usage:*\n\nExample:\n• \`!meet Tomorrow at 3 PM with client@gmail.com for Project Discussion\`\n• \`!meet Next Monday 10:00 AM to 11:00 AM with team@gmail.com\`\n\nI will automatically create the Google Calendar event, generate a Google Meet link, and invite all email addresses!`
            },
            { quoted: msg }
          );
          return;
        }

        logger.info({ chatId, senderName, prompt: schedulePrompt }, 'Processing meeting schedule command');
        await sock.sendMessage(chatId, { text: '⏳ *Scheduling meeting and setting up Google Meet...*' }, { quoted: msg });
        const reply = await aiService.handleMeetingSchedule(schedulePrompt, senderName);
        await sock.sendMessage(chatId, { text: reply }, { quoted: msg });
        return;
      }

      // Group Admin Commands: !kick / !remove, !add, !promote, !demote, !invite, !link
      if (
        lowerText.startsWith('!kick') ||
        lowerText.startsWith('!remove') ||
        lowerText.startsWith('!add') ||
        lowerText.startsWith('!promote') ||
        lowerText.startsWith('!demote') ||
        lowerText.startsWith('!invite') ||
        lowerText.startsWith('!link') ||
        lowerText.startsWith(`${config.commandPrefix} kick`) ||
        lowerText.startsWith(`${config.commandPrefix} remove`) ||
        lowerText.startsWith(`${config.commandPrefix} add`) ||
        lowerText.startsWith(`${config.commandPrefix} promote`) ||
        lowerText.startsWith(`${config.commandPrefix} demote`) ||
        lowerText.startsWith(`${config.commandPrefix} invite`)
      ) {
        if (!isGroup) {
          await sock.sendMessage(chatId, { text: 'ℹ️ Group moderation commands only work in group chats.' }, { quoted: msg });
          return;
        }

        let action = '';
        if (lowerText.startsWith('!kick') || lowerText.startsWith('!remove') || lowerText.startsWith(`${config.commandPrefix} kick`) || lowerText.startsWith(`${config.commandPrefix} remove`)) action = 'remove';
        else if (lowerText.startsWith('!add') || lowerText.startsWith(`${config.commandPrefix} add`)) action = 'add';
        else if (lowerText.startsWith('!promote') || lowerText.startsWith(`${config.commandPrefix} promote`)) action = 'promote';
        else if (lowerText.startsWith('!demote') || lowerText.startsWith(`${config.commandPrefix} demote`)) action = 'demote';
        else if (lowerText.startsWith('!invite') || lowerText.startsWith('!link') || lowerText.startsWith(`${config.commandPrefix} invite`)) action = 'invite';

        await this.handleGroupModeration(sock, msg, chatId, action, trimmedText, isFromMe, senderJid);
        return;
      }

      // Summarize command in groups
      if (lowerText.startsWith('!summarize') || lowerText.startsWith(`${config.commandPrefix} summarize`)) {
        if (!isGroup) {
          await sock.sendMessage(chatId, { text: 'ℹ️ The `!summarize` command is meant for group chats to summarize recent discussions.' }, { quoted: msg });
          return;
        }

        const countMatch = trimmedText.match(/\d+/);
        const count = countMatch ? Math.min(parseInt(countMatch[0], 10), 50) : 25;

        const history = recentGroupMessages.get(chatId) || [];
        const messagesToSummarize = history.slice(-count).map(m => `[${m.time}] ${m.sender}: ${m.text}`);

        if (messagesToSummarize.length < 3) {
          await sock.sendMessage(chatId, { text: 'ℹ️ Not enough recent messages recorded yet to generate a summary. Keep chatting and try again!' }, { quoted: msg });
          return;
        }

        await sock.sendMessage(chatId, { text: '⏳ *Analyzing and summarizing recent group messages...*' }, { quoted: msg });
        const summary = await aiService.summarizeMessages(messagesToSummarize);
        await sock.sendMessage(chatId, { text: `📊 *Group Chat Summary (Last ${messagesToSummarize.length} messages):*\n\n${summary}` }, { quoted: msg });
        return;
      }

      // Auto-reply mode toggle command: !autoreply on / !autoreply off / !autoreply status
      if (
        lowerText === '!autoreply' ||
        lowerText.startsWith('!autoreply ') ||
        lowerText === '!auto' ||
        lowerText.startsWith('!auto ') ||
        lowerText === `${config.commandPrefix} autoreply` ||
        lowerText.startsWith(`${config.commandPrefix} autoreply `)
      ) {
        const parts = lowerText.split(/\s+/);
        const subcommand = parts[1]?.toLowerCase();

        if (subcommand === 'on' || subcommand === 'enable' || subcommand === 'true') {
          botSettings.setAutoReplyDms(true);
          await sock.sendMessage(
            chatId,
            { text: '🤖 *Auto-Reply Mode: ON*\n\nThe bot will now automatically respond to all incoming direct messages (DMs) without needing `@bot` or `!ai`.' },
            { quoted: msg }
          );
          return;
        } else if (subcommand === 'off' || subcommand === 'disable' || subcommand === 'false') {
          botSettings.setAutoReplyDms(false);
          await sock.sendMessage(
            chatId,
            { text: '🔇 *Auto-Reply Mode: OFF (Tag / Command Only)*\n\nThe bot will now only reply when explicitly tagged (@bot) or commanded with `!ai`.' },
            { quoted: msg }
          );
          return;
        } else {
          const status = botSettings.autoReplyDms ? '🟢 *ENABLED (Auto-answers DMs)*' : '🔴 *DISABLED (Only answers when tagged or commanded)*';
          await sock.sendMessage(
            chatId,
            {
              text: `⚙️ *Auto-Reply Setting:* ${status}\n\n• Turn ON: \`!autoreply on\`\n• Turn OFF: \`!autoreply off\``
            },
            { quoted: msg }
          );
          return;
        }
      }

      // Explicit AI Command: !ai <prompt>
      if (lowerText.startsWith(config.commandPrefix)) {
        const prompt = trimmedText.slice(config.commandPrefix.length).trim();
        if (!prompt) {
          await sock.sendMessage(chatId, { text: `👋 Hi ${senderName}! How can I help you? Ask me anything by typing \`${config.commandPrefix} <your question>\`.` }, { quoted: msg });
          return;
        }

        // Check if prompt is a group moderation request in natural language
        if (isGroup && this.isGroupModerationIntent(prompt)) {
          const modAction = this.extractModerationAction(prompt);
          if (modAction) {
            await this.handleGroupModeration(sock, msg, chatId, modAction, prompt, isFromMe, senderJid);
            return;
          }
        }

        // Check if prompt is a meeting scheduling request
        if (this.isMeetingIntent(prompt)) {
          logger.info({ chatId, senderName, prompt }, 'Detected meeting scheduling intent in AI prompt');
          await sock.sendMessage(chatId, { text: '⏳ *Scheduling meeting and setting up Google Meet...*' }, { quoted: msg });
          const reply = await aiService.handleMeetingSchedule(prompt, senderName);
          await sock.sendMessage(chatId, { text: reply }, { quoted: msg });
          return;
        }

        logger.info({ chatId, senderName, prompt }, 'Processing AI command');
        const reply = await aiService.generateReply(chatId, prompt, senderName, isGroup);
        await sock.sendMessage(chatId, { text: reply }, { quoted: msg });
        return;
      }

      // Tag / Mention / Wake Word Trigger (in groups or DMs)
      const myJid = sock.user?.id ? sock.user.id.split(':')[0] + '@s.whatsapp.net' : '';
      const myLid = sock.user?.lid ? sock.user.lid.split(':')[0] + '@lid' : '';
      const isTagged = config.respondOnTag && (this.isUserTagged(msg, myJid) || this.isUserTagged(msg, myLid));
      const hasWakeWord = config.wakeWords.some(w => {
        const regex = new RegExp(`(^|\\s|@)${w}\\b`, 'i');
        return regex.test(lowerText);
      });

      if (isTagged || hasWakeWord) {
        // Clean prompt from tags / wake words
        let cleanedPrompt = trimmedText;
        if (myJid) {
          const myNum = myJid.split('@')[0];
          cleanedPrompt = cleanedPrompt.replace(new RegExp(`@${myNum}`, 'gi'), '').trim();
        }
        if (myLid) {
          const myLidNum = myLid.split('@')[0];
          cleanedPrompt = cleanedPrompt.replace(new RegExp(`@${myLidNum}`, 'gi'), '').trim();
        }
        config.wakeWords.forEach(w => {
          cleanedPrompt = cleanedPrompt.replace(new RegExp(`^@?${w}[: ,]?`, 'gi'), '').trim();
        });

        if (!cleanedPrompt) {
          await sock.sendMessage(
            chatId,
            { text: `👋 Hi ${senderName}! I'm listening. Ask me anything or type \`${config.commandPrefix} <your question>\` or \`!meet ...\`.` },
            { quoted: msg }
          );
          return;
        }

        if (isGroup && this.isGroupModerationIntent(cleanedPrompt)) {
          const modAction = this.extractModerationAction(cleanedPrompt);
          if (modAction) {
            await this.handleGroupModeration(sock, msg, chatId, modAction, cleanedPrompt, isFromMe, senderJid);
            return;
          }
        }

        if (this.isMeetingIntent(cleanedPrompt)) {
          logger.info({ chatId, senderName, prompt: cleanedPrompt }, 'Responding to tagged meeting schedule intent');
          await sock.sendMessage(chatId, { text: '⏳ *Scheduling meeting and setting up Google Meet...*' }, { quoted: msg });
          const reply = await aiService.handleMeetingSchedule(cleanedPrompt, senderName);
          await sock.sendMessage(chatId, { text: reply }, { quoted: msg });
          return;
        }

        logger.info({ chatId, senderName, prompt: cleanedPrompt }, 'Responding to tag / mention / wake word');
        const reply = await aiService.generateReply(chatId, cleanedPrompt, senderName, isGroup);
        await sock.sendMessage(chatId, { text: reply }, { quoted: msg });
        return;
      }

      // Auto-reply to DMs if enabled in settings
      if (!isGroup && !isFromMe && botSettings.autoReplyDms && trimmedText.length > 0) {
        logger.info({ chatId, senderName }, 'Auto-replying to unprompted DM');
        const reply = await aiService.generateReply(chatId, trimmedText, senderName, false);
        await sock.sendMessage(chatId, { text: reply }, { quoted: msg });
        return;
      }

    } catch (err: any) {
      logger.error({ err }, 'Error in messageHandler');
    }
  }

  /**
   * Handles group participant actions: add, remove/kick, promote, demote, invite link
   */
  private async handleGroupModeration(
    sock: WASocket,
    msg: WAMessage,
    chatId: string,
    action: 'add' | 'remove' | 'promote' | 'demote' | 'invite',
    rawText: string,
    isFromMe: boolean,
    senderJid: string
  ): Promise<void> {
    try {
      const groupMeta = await sock.groupMetadata(chatId);
      const myNum = (sock.user?.id || '').split(':')[0].split('@')[0];
      const myLidNum = (sock.user?.lid || '').split(':')[0].split('@')[0];

      // Match bot in group participants using phone number or LID
      const botMember = groupMeta.participants.find(p => 
        (myNum && p.id.includes(myNum)) || (myLidNum && p.id.includes(myLidNum))
      );
      const isBotAdmin = botMember?.admin === 'admin' || botMember?.admin === 'superadmin';

      // Invite link generation
      if (action === 'invite') {
        if (!isBotAdmin) {
          await sock.sendMessage(chatId, { text: '⚠️ I need to be a *Group Admin* to generate the group invite link!' }, { quoted: msg });
          return;
        }
        const inviteCode = await sock.groupInviteCode(chatId);
        await sock.sendMessage(chatId, { text: `🔗 *Group Invite Link:*\nhttps://chat.whatsapp.com/${inviteCode}` }, { quoted: msg });
        return;
      }

      // Check bot admin permissions
      if (!isBotAdmin) {
        await sock.sendMessage(
          chatId,
          { text: `⚠️ I cannot *${action}* members because my account is not recognized as a *Group Admin* in this group. Please make sure I am an Admin.` },
          { quoted: msg }
        );
        return;
      }

      // Check sender admin permissions
      const senderNum = senderJid.split(':')[0].split('@')[0];
      const senderMember = groupMeta.participants.find(p => 
        (senderNum && p.id.includes(senderNum)) || (myLidNum && p.id.includes(myLidNum)) || (myNum && p.id.includes(myNum))
      );
      const isSenderAdmin = isFromMe || senderMember?.admin === 'admin' || senderMember?.admin === 'superadmin';

      if (!isSenderAdmin) {
        await sock.sendMessage(
          chatId,
          { text: `⛔ *Permission Denied:* Only *Group Admins* or the bot owner can use moderation commands.` },
          { quoted: msg }
        );
        return;
      }

      const isCommunityLinked = Boolean(groupMeta.linkedParentJid || (groupMeta as any).isCommunity || (groupMeta as any).isCommunityAnnounce);

      // Extract target participant JIDs
      const rawTargetJids: string[] = [];

      // 1. Tagged / Mentioned users in message
      const mentionedJids = msg.message?.extendedTextMessage?.contextInfo?.mentionedJid || [];
      mentionedJids.forEach(j => {
        if (!rawTargetJids.includes(j)) rawTargetJids.push(j);
      });

      // 2. Quoted message author (Crucial for Community groups with hidden phone numbers / LIDs)
      const quotedParticipant = msg.message?.extendedTextMessage?.contextInfo?.participant;
      if (quotedParticipant && !rawTargetJids.includes(quotedParticipant)) {
        rawTargetJids.push(quotedParticipant);
      }

      // 3. Raw phone numbers in text (e.g. +919876543210 or 7550066128)
      const phoneMatches = rawText.match(/\+?\d{8,15}/g) || [];
      phoneMatches.forEach(num => {
        const clean = num.replace(/\+/g, '').trim();
        if (!rawTargetJids.includes(clean)) rawTargetJids.push(clean);
      });

      // Match targets to actual group participant IDs (or construct JID for 'add')
      const targetJids: string[] = [];
      for (const t of rawTargetJids) {
        let cleanTarget = t.replace(/[^0-9]/g, '');

        // Auto-normalize 10-digit Indian numbers (e.g. 7871640149 -> 917871640149)
        if (cleanTarget.length === 10 && /^[6-9]/.test(cleanTarget)) {
          cleanTarget = `91${cleanTarget}`;
        } else if (cleanTarget.length === 11 && cleanTarget.startsWith('0')) {
          cleanTarget = `91${cleanTarget.slice(1)}`;
        }

        // Search in existing group participants (checks exact match, phone match, or LID match)
        const matchedMember = groupMeta.participants.find(p => 
          p.id === t || 
          p.id.includes(cleanTarget) || 
          (p.id.split('@')[0].includes(cleanTarget))
        );

        if (matchedMember) {
          if (!targetJids.includes(matchedMember.id)) targetJids.push(matchedMember.id);
        } else {
          // If action is 'add', build standard JID
          const formattedJid = t.includes('@') ? t : `${cleanTarget}@s.whatsapp.net`;
          if (!targetJids.includes(formattedJid)) targetJids.push(formattedJid);
        }
      }

      if (targetJids.length === 0) {
        await sock.sendMessage(
          chatId,
          {
            text: `⚠️ *Please specify the target user!*\n\n• *Reply:* Quote their message and type \`!${action}\` *(Recommended for Communities)*\n• *Tag:* \`!${action} @user\`\n• *Phone:* \`!${action} +919876543210\``
          },
          { quoted: msg }
        );
        return;
      }

      logger.info({ chatId, action, targetJids, isCommunityLinked }, 'Executing group participants update');
      const response = await sock.groupParticipantsUpdate(chatId, targetJids, action);
      logger.info({ response }, 'Group participants update response');

      // Process detailed result statuses from WhatsApp
      if (Array.isArray(response) && response.length > 0) {
        for (const res of response) {
          const resJid = res.jid || targetJids[0];
          const cleanResNum = resJid.split('@')[0];
          const statusCode = String(res.status);

          if (statusCode === '200') {
            const actionLabels: Record<string, string> = {
              add: '➕ Added to group',
              remove: '🚫 Removed from group',
              promote: '⭐ Promoted to Admin',
              demote: '🔻 Demoted from Admin'
            };
            await sock.sendMessage(
              chatId,
              { text: `✅ *${actionLabels[action] || action}:* @${cleanResNum}`, mentions: [resJid] },
              { quoted: msg }
            );
          } else if (statusCode === '403' || statusCode === '400') {
            // Privacy setting or Community restriction prevents direct addition -> generate invite link
            const inviteCode = await sock.groupInviteCode(chatId).catch(() => '');
            let inviteMsg = isCommunityLinked
              ? `ℹ️ In *WhatsApp Communities*, members cannot be added directly by phone number.`
              : `⚠️ Cannot add @${cleanResNum} directly due to their WhatsApp privacy settings.`;
            if (inviteCode) {
              inviteMsg += `\n\n🔗 *Please share this invite link for them to join:*\nhttps://chat.whatsapp.com/${inviteCode}`;
            }
            await sock.sendMessage(chatId, { text: inviteMsg, mentions: [resJid] }, { quoted: msg });
          } else if (statusCode === '409') {
            await sock.sendMessage(
              chatId,
              { text: `ℹ️ @${cleanResNum} is already in the group.`, mentions: [resJid] },
              { quoted: msg }
            );
          } else if (statusCode === '408') {
            await sock.sendMessage(
              chatId,
              { text: `⏳ Invitation or request for @${cleanResNum} timed out.`, mentions: [resJid] },
              { quoted: msg }
            );
          } else {
            const inviteCode = await sock.groupInviteCode(chatId).catch(() => '');
            let errMsg = `⚠️ Could not ${action} @${cleanResNum} (Status: ${statusCode}).`;
            if (inviteCode && action === 'add') {
              errMsg += `\n\n🔗 *You can invite them with this link:*\nhttps://chat.whatsapp.com/${inviteCode}`;
            }
            await sock.sendMessage(chatId, { text: errMsg, mentions: [resJid] }, { quoted: msg });
          }
        }
      } else {
        const targetMentions = targetJids.map(j => `@${j.split('@')[0]}`).join(', ');
        await sock.sendMessage(
          chatId,
          { text: `✅ *Updated group:* ${targetMentions}`, mentions: targetJids },
          { quoted: msg }
        );
      }
    } catch (err: any) {
      logger.error({ err, chatId, action }, 'Failed to update group participants');
      await sock.sendMessage(
        chatId,
        { text: `⚠️ Failed to ${action} participant: ${err.message || 'Unknown error. Verify bot has admin rights.'}` },
        { quoted: msg }
      );
    }
  }

  private isGroupModerationIntent(text: string): boolean {
    const lower = text.toLowerCase();
    const modKeywords = [
      'remove ',
      'kick ',
      'remove user',
      'kick user',
      'add ',
      'add user',
      'promote ',
      'demote ',
      'make admin',
      'remove admin',
      'group link',
      'invite link'
    ];
    return modKeywords.some(kw => lower.includes(kw));
  }

  private extractModerationAction(text: string): 'add' | 'remove' | 'promote' | 'demote' | 'invite' | null {
    const lower = text.toLowerCase();
    if (lower.includes('kick') || lower.includes('remove ') || lower.includes('kick user') || lower.includes('remove user')) return 'remove';
    if (lower.includes('add ') || lower.includes('add user') || lower.includes('invite user')) return 'add';
    if (lower.includes('promote') || lower.includes('make admin')) return 'promote';
    if (lower.includes('demote') || lower.includes('remove admin')) return 'demote';
    if (lower.includes('group link') || lower.includes('invite link')) return 'invite';
    return null;
  }

  /**
   * Helper to extract string text from varied WhatsApp message types
   */
  private extractTextContent(message?: proto.IMessage | null): string {
    if (!message) return '';
    return (
      message.conversation ||
      message.extendedTextMessage?.text ||
      message.imageMessage?.caption ||
      message.videoMessage?.caption ||
      message.documentMessage?.caption ||
      ''
    );
  }

  /**
   * Checks if user is tagged in message contextInfo
   */
  private isUserTagged(msg: WAMessage, userJid: string): boolean {
    if (!userJid) return false;
    const mentionedJids = msg.message?.extendedTextMessage?.contextInfo?.mentionedJid || [];
    const myCleanNumber = userJid.split('@')[0];
    return mentionedJids.some(jid => jid.includes(myCleanNumber));
  }

  private isMentionedOrCommanded(msg: WAMessage, text: string, myJid?: string): boolean {
    if (this.isUserTagged(msg, myJid || '')) return true;
    const lower = text.toLowerCase();
    return (
      lower.startsWith(config.commandPrefix) ||
      config.wakeWords.some(w => lower.includes(w))
    );
  }

  private cacheGroupMessage(chatId: string, sender: string, text: string) {
    if (!recentGroupMessages.has(chatId)) {
      recentGroupMessages.set(chatId, []);
    }
    const history = recentGroupMessages.get(chatId)!;
    const time = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    history.push({ sender, text, time });
    if (history.length > 50) {
      history.shift();
    }
  }

  /**
   * Detects if a text prompt contains intent to schedule a meeting/event
   */
  private isMeetingIntent(text: string): boolean {
    const lower = text.toLowerCase();
    const meetingKeywords = [
      'schedule a meet',
      'schedule a meeting',
      'schedule meet',
      'schedule meeting',
      'create a meet',
      'create a meeting',
      'set up a meet',
      'set up a meeting',
      'book a meet',
      'book a meeting',
      'google meet',
      'calendar invite',
      'add to calendar',
      'meeting on',
      'meet on',
      'meet at',
      'meeting at',
      'meeting tomorrow',
      'meet tomorrow'
    ];
    return meetingKeywords.some(kw => lower.includes(kw));
  }

  private getHelpMessage(): string {
    return `🤖 *WhatsApp AI Assistant - Commands & Features*

• \`${config.commandPrefix} <prompt>\` : Ask anything to the AI
• \`!autoreply on / off\` : Toggle auto-answering DMs on or off
• \`!meet <details>\` : Schedule a meeting, Google Meet & invite emails (e.g. \`!meet Tomorrow at 4 PM with colleague@gmail.com for Sync\`)
• \`!summarize [number]\` : Summarize recent group chat messages (e.g. \`!summarize 20\`)
• \`!ping\` : Check bot connection and status
• \`!help\` : Show this help menu

👥 *Group Admin & Moderation Commands*:
• \`!add <phone_number>\` : Add a user to group (e.g. \`!add +919876543210\`)
• \`!kick\` or \`!remove <@user>\` : Remove member from group (or reply to their message with \`!kick\`)
• \`!promote <@user>\` : Make member an admin
• \`!demote <@user>\` : Remove admin status
• \`!invite\` or \`!link\` : Get group invite link

📅 *Google Meet & Calendar Scheduling*:
Schedule meetings in natural language! Say:
_\`!meet Friday 3:00 PM with alice@gmail.com for Design Review\`_

🎙️ *Voice Notes & Audio*:
Send or forward any voice note, and I will automatically transcribe and summarize it for you!

💬 *Group Chat Triggers*:
Tag me (@me) or use wake words (*${config.wakeWords.join(', ')}*) or use \`${config.commandPrefix}\` in any group.`;
  }
}

export const messageHandler = new MessageHandler();

